# Generated by Django 5.1.1 on 2024-09-09 05:20

import core.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[core.models.validate_resturent_name_begins_with_a])),
                ('website', models.URLField(default='')),
                ('date_opened', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('resturent_type', models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinise'), ('IT', 'Italian'), ('GR', 'GREEK'), ('MD', 'Mexican'), ('FD', 'FastFood'), ('OT', 'Other')], max_length=2)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.resturent')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_time', models.DateTimeField()),
                ('resturent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.resturent')),
            ],
        ),
        migrations.CreateModel(
            name='StaffResturent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(null=True)),
                ('resturent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resturent')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='resturent',
            field=models.ManyToManyField(through='core.StaffResturent', to='core.resturent'),
        ),
    ]
