# Generated by Django 5.0.3 on 2024-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
