# Generated by Django 5.1.1 on 2024-09-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='resturent_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinise'), ('IT', 'Italian'), ('GR', 'GREEK'), ('MD', 'Mexican'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
