# Generated by Django 5.1.1 on 2024-09-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resturent_resturent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_time', models.DateTimeField()),
                ('resturent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.resturent')),
            ],
        ),
    ]
