# Generated by Django 5.0.3 on 2024-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resturent_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
