# Generated by Django 5.0.3 on 2024-09-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_resturent_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(3, '3 Days'), (7, '7 Days'), (15, '15 Days'), (30, '30 Days')])),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Premium', 'Premium')], max_length=30)),
                ('per_meal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('service_id', models.CharField(max_length=10, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/profile')),
                ('flexibility', models.IntegerField(default=0)),
                ('flexibility_used', models.IntegerField(default=0)),
                ('reduce_balance', models.BooleanField(default=True, help_text='Uncheck to stop balance reduction of this user')),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.package')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=10)),
                ('sender_number', models.CharField(max_length=15)),
                ('transaction_id', models.CharField(max_length=30)),
                ('plan', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.dashboard')),
            ],
        ),
    ]
