# Generated by Django 5.0.3 on 2024-09-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgressTask',
            fields=[
            ],
            options={
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.task',),
        ),
        migrations.AlterField(
            model_name='resturent',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
