# Generated by Django 5.0.3 on 2024-09-15 06:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inprogresstask_alter_resturent_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('income'), '-', models.F('expenditure')), output_field=models.DecimalField(decimal_places=2, max_digits=5)),
        ),
    ]
